### ISSUE TITLE
allow control of HTTP content type

### ISSUE THREAD

**Issue by simonmichael** [tdammers/sprinkles#1]
Thanks for sharing this great tool. I am working on reproducing my hakyll-based site, and it's going quite well!

Now I'm generating a blog feed, but I think it's not possible to set the `application/xml` content type. Could this be added ?

**Comment by tdammers** [comment]
The "proper" solution for this, I believe, would be to add support for an XML output writer - the code is structured in a modular fashion already, so adding, say, an XSLT converter would be possible. Even more properly, I've been pondering a "pipeline" system, where you could just chain output transformers however you like, which would also fold templates, static file serving, JSON transforms, XML transforms, and even data backends, into the same general mechanism.

Short term, however, I think a simple content type override is the pragmatic solution; I'll see what I can come up with, shouldn't be difficult at all.

**Comment by tdammers** [comment]
OK, here's the short term solution. It's a bit dangerous though, as in, the content type override does not do any checks, it just takes the output from whatever your routing rule produces, and replaces the `Content-type` header with whatever you specify, so if you tell Sprinkles to serve something as XML that comes from an HTML template, it will just do that without any further checks.

It also only works for template output currently, that is, you can't override the content type for JSON and static responses right now.

**Comment by simonmichael** [comment]
Thank you very much!

**Comment by simonmichael** [comment]
I am generating both dynamic and static versions of the feed, like so:
```yaml
  # /_blog.xml - draft blog feed, for review                                                                                                                                                                    
  - pattern: '/_blog.xml'                                                                                                                                                                                       
    template: 'blog-feed.html'                                                                                                                                                                                  
    content-type: 'application/xml'                                                                                                                                                                             
    data:                                                                                                                                                                                                       
      posts:                                                                                                                                                                                                    
        type: 'dir'                                                                                                                                                                                             
        path: 'blog'                                                                                                                                                                                            
        #fetch: {{settings.feed.size}}                                                                                                                                                                          
        #fetch: {{settings.feed["size"]}}                                                                                                                                                                       
        fetch: 11                                                                                                                                                                                               
        order: '-name'                                                                                                                                                                                          
                                                                                                                                                                                                                
  # /blog.xml - actual blog feed (static manual snapshot of _blog.xml)                                                                                                                                          
  - pattern: '/blog.xml'                                                                                                                                                                                        
    static: true                                                                                                                                                                                                
    content-type: 'application/xml'                                                                                                                                                                             
    data:                                                                                                                                                                                                       
      file: 'file://./blog.xml'                                                                                                                                                                                 
```

This is both for safety, to prevent mistakes affecting all feed readers, and performance (the naive dynamic version takes several seconds, unfortunately). With the first route I see the expected `application/xml` type, but the second (static) one gives type `text/xml`. Maybe that's ok and correct.
