### ISSUE TITLE
sprinkles -serve uses old template

### ISSUE THREAD

**Issue by andrewufrank** [tdammers/sprinkles#17]
I try to move from the first example to a different template. I change the index file to one with an error and get the error report from sprinkel `line 3, column 1: unexpected " "`. I rename the index.html file to something else (indexWithBase.html) and create a new, fixed index.html. no change in the project.yml file. 
sprinkles -serve returns the same error as before and the line has the indexfile name i changed the old one to: 
````
sprinkles -serve 5000
ServeProject (ServerConfig {scBackendCache = [], scDriver = WarpDriver (Just 5000), scLogger = Nothing, scSessions = SessionConfig {sessCookieName = "ssid", sessCookieSecure = True, sessExpiration = NeverExpire, sessDriver = NoSessionDriver}, scRootDir = ""})
In 'indexWithBase.html': line 3, column 1: unexpected " "
````
the config is: 
````
rules:
- pattern: '/'
#  data:
 #   page: 'file://./data/pages/home.markdown' 
  template: 'index.html'
- pattern: '/{{page:*}}'
  data:
    page: 'file://./data/pages/{{page}}.markdown'
  template: 'page.html'
- pattern: '/static/{{path:**}}'
  data:
    file: 'file://./static/{{path}}'
  static: true
````
Is there some caching and where? How to clean it out - opening a new terminal did not help.
I am baffled - what did I do wrong? Changing the template to `indexXX.html` which does not exist produces the same error msg as before (with reference to the `indexWithBase.html` file. 
The strange behaviour stops when I finally delete the 'indexWithBase.html` and I get another error message.

could you add to the decoumentation when a `sprinkes -serve` is automatically considering the new inputs and when it must be restarted to use new inputs? I assume that templates are read in only initially and chanes there require restart of sprinkles, conent files however not. What is cached between runs? I am confused at the moment.
