### ISSUE TITLE
Pipelining

### ISSUE THREAD

**Issue by tdammers** [tdammers/sprinkles#4]
Something I've wanted for a while now was the ability to "pipeline" rules, that is, build rules by chaining multiple rules together. After all, the data coming out of data sources in a rule are of the same kind of shape as what ultimately gets served.

Turns out there is a blatantly simple solution to this: Just make a new backend type that fetches data from a rule, sort of like an internal subrequest. Something like:

```yaml
rules:
  - pattern: '/foobar/json/{{item:*}}'
    data:
    - thing: 'file://./data/{{item}}'
    template: 'item.json'
    content-type: 'application/json'
  - pattern: '/foobar/html/{{item:*}}'
    data:
    - thing: 'self:///foobar/json/{{item}}'
    template: 'item.html'
```
