### ISSUE TITLE
Document global variables (top-level `data:`)

### ISSUE THREAD

**Issue by ad-si** [tdammers/sprinkles#9]
It would be cool if there was a field in the project.yml to define global variables. e.g.

```yaml
global:
   site_url: example.org
   items_per_page: 10
rules:
  …
```

or is there already a way to accomplish this?
